In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

from sklearn.preprocessing import OneHotEncoder

In [6]:
###dataset

data = pd.read_csv("d:/project/ann1/Churn_Modelling.csv")

In [7]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [8]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary  Exited
0             1    15634602   Hargrave  ...               1       101348.88       1
1             2    15647311       Hill  ...               1       112542.58       0
2             3    15619304       Onio  ...               0       113931.57       1
3             4    15701354       Boni  ...               0        93826.63       0
4             5    15737888   Mitchell  ...               1        79084.10       0
...         ...         ...        ...  ...             ...             ...     ...
9995       9996    15606229   Obijiaku  ...               0        96270.64       0
9996       9997    15569892  Johnstone  ...               1       101699.77       0
9997       9998    15584532        Liu  ...               1        42085.58       1
9998       9999    15682355  Sabbatini  ...               0        92888.52       1
9999      10000    15628319     Walker  ...               0        38190.78       0

[10000 rows x 14 columns]

In [10]:

### onehot encde geography column

onehot_encoder = OneHotEncoder()
geo_encoder = onehot_encoder.fit_transform(data[["Geography"]])

geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [12]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [11]:
onehot_encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [ ]:
##### converting geography to onehot encoding
#### 1 use ohe() on column with .toarray()

geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
###combining ohe with og

data = pd.concat([data.drop('Geography', axis =1), geo_encoded_df], axis = 1)

data.head()

   RowNumber  CustomerId  ... Geography_Germany  Geography_Spain
0          1    15634602  ...               0.0              0.0
1          2    15647311  ...               0.0              1.0
2          3    15619304  ...               0.0              0.0
3          4    15701354  ...               0.0              0.0
4          5    15737888  ...               0.0              1.0

[5 rows x 16 columns]

In [24]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [18]:
### saving encoders and scaler


with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)


with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(onehot_encoder, file)

In [25]:
###divide data in x and y


X = data.drop('Exited', axis=1)
y = data['Exited']

#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [52]:
with open('sc.pkl', 'wb') as file:
    pickle.dump(sc, file)

In [27]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

ANN implementation'

In [30]:
X_train.shape

(8000, 12)

In [28]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [31]:
###model

model_1 = Sequential([
    Dense(64, input_shape=(X_train.shape[1],), activation='relu'), ##l1
    Dense(32, activation='relu'), ##l2
    Dense(1, activation='sigmoid')
])

d:\project\ann1\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [32]:
model_1.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
model_1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [48]:
log_dir = "../logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [38]:
###early stopping

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

In [39]:
print("Fit model on training data")
history = model_1.fit(
    X_train,
    y_train,
    batch_size=64,
    epochs=100,
    # We pass some validation for
    # monitoring validation loss and metrics
    # at the end of each epoch
    validation_data=(X_test, y_test),
    callbacks=[tensorboard_callback, early_stopping]
)

Fit model on training data
Epoch 1/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7598 - loss: 0.5035 - val_accuracy: 0.8200 - val_loss: 0.4136
Epoch 2/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8310 - loss: 0.4065 - val_accuracy: 0.8390 - val_loss: 0.3774
Epoch 3/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8499 - loss: 0.3744 - val_accuracy: 0.8560 - val_loss: 0.3555
Epoch 4/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8549 - loss: 0.3554 - val_accuracy: 0.8565 - val_loss: 0.3501
Epoch 5/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8612 - loss: 0.3468 - val_accuracy: 0.8540 - val_loss: 0.3485
Epoch 6/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8601 - loss: 0.3420 - val_accuracy: 0.8590 - val_loss: 0.3482
Epoch 7/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8600 - loss: 0.3393 - val_accuracy: 0.8515 - val_loss: 0.3521
Epoch 8/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8624 - loss: 0.3374 - val_accuracy: 0.8560 - val_loss: 0.3472
Epoch 9/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8633 - loss: 0.3343 - val_accuracy: 0.8635 - val_loss: 0.3451
Epoch 10/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8629 - loss: 0.3321 - val_accuracy: 0.8585 - val_loss: 0.3471
Epoch 11/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3316 - val_accuracy: 0.8610 - val_loss: 0.3466
Epoch 12/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8635 - loss: 0.3298 - val_accuracy: 0.8555 - val_loss: 0.3478
Epoch 13/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8643 - loss: 0.3271 - val_accuracy: 0.8585 - val_loss: 0.3482
Epoch 14/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8658 - loss: 0.3257 - val_accuracy: 0.8575 - val_loss: 0.3466

In [43]:
model_1.save('model1.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [49]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [51]:
%tensorboard --logdir ../logs/fit

Reusing TensorBoard on port 6007 (pid 35240), started 0:05:11 ago. (Use '!kill 35240' to kill it.)